GET http://localhost:3000/students/

###

GET http://localhost:3000/students/639b4341d009bbdd3c3136d2

###

POST http://localhost:3000/students/

###

DELETE http://localhost:3000/students/:id

###

PUT http://localhost:3000/students/:id