import {
  getAllSchools,
  getSchool,
  addNewSchool,
  deleteSchool,
  updateSchool,
  addStudent,
  removeStudent,
  addTeacher,
  removeTeacher,
  addClass,
  removeClass,
  updateClass,
  registerSchool,
  loginSchool,
} from "./schools.controller.js";

import {
  getAllStudents,
  getStudent,
  addNewStudent,
  deleteStudent,
  updateStudent,
  registerStudent,
  loginStudent,
} from "./students.controller.js";

import {
  getAllTeachers,
  getTeacher,
  addNewTeacher,
  deleteTeacher,
  updateTeacher,
  registerTeacher,
  loginTeacher,
} from "./teachers.controller.js";

//Export all controller functions
export default {
  getAllSchools,
  getSchool,
  addNewSchool,
  deleteSchool,
  updateSchool,
  registerSchool,
  loginSchool,
  addStudent,
  removeStudent,
  addTeacher,
  removeTeacher,
  addClass,
  removeClass,
  updateClass,
  getAllStudents,
  getStudent,
  addNewStudent,
  deleteStudent,
  updateStudent,
  registerStudent,
  loginStudent,
  getAllTeachers,
  getTeacher,
  addNewTeacher,
  deleteTeacher,
  updateTeacher,
  registerTeacher,
  loginTeacher,
};
